---

- hosts: local
  vars:
    qemu_config: "{{ lookup('file', 'qemu-config.yml') | from_yaml }}"
  tasks:

    - name: get ips for invenotry hostnames
      include_tasks: 'get-ips.yml'
      loop_control:
        index_var: i
      loop: '{{ qemu_config }}'

    - name: copy ip4 adress to qemu config file
      copy:
        content: '{{ qemu_config | to_nice_yaml }}'
        dest: 'qemu-config.yml'

    - name: create ssh config
      template:
        src: 'templates/ssh_config.j2'
        dest: 'ssh_config'

    - name: create group_vars folder
      file:
        path: 'group_vars'
        state: directory

    - name: add ssh_config to qemu vm group_vars
      copy:
        content: |
          ---
          ansible_ssh_common_args: "-F ssh_config"
        dest: 'group_vars/qemu.yml'

- hosts: qemu
  tasks:
    - name: set hostname
      command: 'hostnamectl set-hostname {{ inventory_hostname }}'
      register: hostname_update

    - name: restart network to register hostname on dns server
      service:
        name: network
        state: restarted
      when: hostname_update.changed

    - name: set ssh private key
      copy:
        src: '{{ ssh.identity_file }}'
        dest: '/root/.ssh/id_rsa'
        owner: '{{ ssh.user }}'
        group: '{{ ssh.user }}'
        mode: '0600'