---

- name: remove vm config from global qemu config
  set_fact:
    qemu_config: '{{ qemu_config | difference([item]) }}'

- name: get qemu network interfaces from Proxmox api
  command: '{{ pve_api }} getNetworkInterfaces {{ item.id }}'
  register: network_interfaces
  check_mode: no

- name: extract public interface
  set_fact: network_interfaces_list='{{ network_interfaces.stdout | from_json }}'

#- debug: var=network_interfaces_list

- name: extract ip4 from public/second interface
  set_fact: ip4_addr='{{ network_interfaces_list[1]["IPAddresses"][0] }}'

- name: combine ip4 address with vm config item
  set_fact:
    item_with_ip: '{{ item | combine({"ip4": ip4_addr}) }}'

- name: append item to global qemu config
  set_fact:
    qemu_config: '{{ qemu_config + [item_with_ip] }}'
